// import React from "react";
// import { Link } from "react-router-dom";
// const Home = () => {
//   return (
//     <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
//       <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
//       <p style={{ fontSize: "18px", marginBottom: "30px" }}>
//         This project was generated By{" "}
//         <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
//           Dhiwise
//         </a>
//         . Quickly use below links to navigate through all pages.
//       </p>
//       <ul style={{ listStyle: "none", padding: "0" }}>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/register" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Register
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/registerone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             RegisterOne
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/registertwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             RegisterTwo
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/tvone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             TVOne
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/tvtwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             TVTwo
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/tvthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             TVThree
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/login" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Login
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/registerthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             RegisterThree
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/registerfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             RegisterFive
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link to="/profilesetupfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             ProfilesetupFour
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/profilesetuptwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             ProfilesetupTwo
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/profilesetupone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             ProfilesetupOne
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/profilesetupthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             ProfilesetupThree
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/home1" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Home1
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/homeone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeOne
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/hometwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeTwo
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogram" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgram
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramOne
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramtwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramTwo
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramThree
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramFour
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramFive
//             </Link>
//         </li>

//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramsix" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramSix
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramseven" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramSeven
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogrameight" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramEight
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramnine" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramNine
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/academicprogramten" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             AcademicProgramTen
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/home" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeThree
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/homefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeFour
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/homefive" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeFive
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/homesix" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeSix
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/liveevents" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Liveevents
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/liveeventsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             LiveeventsOne
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/liveeventstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             LiveeventsTwo
//             </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//             <Link to="/generalsignup" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             GeneralSignUp
//             </Link>
//         </li>

//         <li style={{ marginBottom: "10px" }}>
//         <Link to="/generalsignup" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             GeneralSignUp
//         </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//         <Link to="/generalsignupone" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             GeneralSignUpOne
//         </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//         <Link to="/generalsignuptwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             GeneralSignUpTwo
//         </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//         <Link to="/generalsignupthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             GeneralSignUpThree
//         </Link>
//         </li>


//       </ul>
//     </div>
//   );
// };

// export default Home;



// import React from "react";
// import { Link } from "react-router-dom";

// const Home = () => {
//   const links = [
//     { path: "/register", label: "Register" },
//     { path: "/dashboard", label: "Dashboard" },
//     { path: "/registertwo", label: "RegisterTwo" },
//     { path: "/tvone", label: "TVOne" },
//     // Add the rest of your links here...
//     { path: "/generalsignupthree", label: "GeneralSignUpThree" }
//   ];

//   return (
//     <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
//       <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
//       <p style={{ fontSize: "18px", marginBottom: "30px" }}>
//         This project was generated By{" "}
//         <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
//           Dhiwise
//         </a>
//         . Quickly use the links below to navigate through all pages.
//       </p>
//       <div style={{ maxHeight: "60vh", overflowY: "auto" }}>
//         <ul style={{ listStyle: "none", padding: "0" }}>
//           {links.map((link, index) => (
//             <li key={index} style={{ marginBottom: "10px" }}>
//               <Link to={link.path} style={{ color: "#87CEFA", textDecoration: "none" }}>
//                 {link.label}
//               </Link>
//             </li>
//           ))}
//         </ul>
//       </div>
//     </div>
//   );
// };

// export default Home;






import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div>
      <h1>Welcome to the Homepage</h1>
      <Link to="/dashboard">Go to Dashboard</Link> {/* Link to navigate to the Dashboard page */}
    </div>
  );
};

export default Home;
